# Generated by Django 3.0.3 on 2020-02-22 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200124_0144'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cite',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='quotes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.CharField(blank=True, help_text='insert tags here for better SEO ', max_length=30),
        ),
    ]
