# Generated by Django 3.0.3 on 2020-02-22 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200222_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cite',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='quotes',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.CharField(help_text='insert tags here for better SEO ', max_length=30),
        ),
    ]
