# Generated by Django 3.0.3 on 2020-02-27 21:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200224_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cite',
            field=models.CharField(blank=True, help_text='leave it empty if quotes are empty', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='quotes',
            field=models.TextField(blank=True, help_text='Not Compulsory'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.CharField(default='Protv', help_text='Insert tags here for better SEO ', max_length=30),
        ),
        migrations.CreateModel(
            name='Commenters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commenter_name', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('comments', models.TextField()),
                ('comment_time', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Post')),
            ],
            options={
                'ordering': ['comment_time'],
            },
        ),
    ]
